<?php

namespace Database\Seeders;

use App\Models\Documentation;
use App\Models\User;
use Illuminate\Database\Seeder;

class DocumentationSeeder extends Seeder
{
    public function run(): void
    {
        $admin = User::role('admin')->first();

        if (!$admin) {
            return;
        }

        foreach ($this->documents() as $doc) {
            Documentation::updateOrCreate(
                [
                    'slug' => $doc['slug'],
                ],
                array_merge($doc, ['created_by' => $admin->id])
            );
        }
    }

    protected function documents(): array
    {
        return [
            // Getting Started
            [
                'slug' => 'getting-started-marketplace',
                'title' => 'Mulai Jual Catatan di Noteds',
                'content' => '<p>Panduan langkah demi langkah membuat catatan, mengatur harga, dan mempublikasikan ke marketplace.</p>',
                'summary' => 'Panduan ringkas memulai penjualan catatan digital.',
                'category' => 'wiki',
                'icon' => 'heroicons-outline:document-text',
                'links' => ['/docs/publish-note', '/docs/pricing-guide'],
                'screenshots' => ['docs/screenshots/create-note.png'],
                'video_urls' => ['https://www.youtube.com/watch?v=dummy123'],
                'tags' => ['marketplace', 'seller', 'pricing'],
                'order' => 1,
                'is_active' => true,
                'view_count' => 135,
                'helpful_count' => 42,
            ],
            [
                'slug' => 'wallet-and-withdraw',
                'title' => 'Kelola Dompet & Withdraw',
                'content' => '<p>Pelajari cara top up saldo, melihat riwayat transaksi, hingga menarik dana ke rekening bank.</p>',
                'summary' => 'Semua hal terkait dompet digital Noteds.',
                'category' => 'screenshot_guide',
                'icon' => 'heroicons-outline:currency-dollar',
                'links' => ['/wallet', '/docs/withdraw-policy'],
                'screenshots' => ['docs/screenshots/wallet-dashboard.png'],
                'video_urls' => [],
                'tags' => ['wallet', 'withdraw', 'finance'],
                'order' => 2,
                'is_active' => true,
                'view_count' => 98,
                'helpful_count' => 30,
            ],
            [
                'slug' => 'ai-tools-overview',
                'title' => 'Eksplorasi Fitur AI Noteds',
                'content' => '<p>Kenali bagaimana AI membantu membuat ringkasan, keyword, hingga rekomendasi harga secara otomatis.</p>',
                'summary' => 'Overview modul AI untuk penjual dan pembeli.',
                'category' => 'video_tutorial',
                'icon' => 'heroicons-outline:sparkles',
                'links' => ['/docs/ai-summary', '/docs/ai-tagging'],
                'screenshots' => [],
                'video_urls' => ['https://www.youtube.com/watch?v=dummy456'],
                'tags' => ['ai', 'automation', 'insight'],
                'order' => 3,
                'is_active' => true,
                'view_count' => 77,
                'helpful_count' => 21,
            ],
            // Sale Mode System
            [
                'slug' => 'sale-mode-system',
                'title' => 'Sistem Mode Penjualan: Scarcity vs Standard',
                'content' => '<p>Pelajari perbedaan antara Scarcity Mode dan Standard Mode, cara mengatur grace period, dan strategi resale untuk meningkatkan revenue.</p><p><strong>Scarcity Mode:</strong> One-time purchase, buyer bisa resell, original creator dapat komisi di setiap penjualan, grace period untuk repurchase.</p><p><strong>Standard Mode:</strong> Multiple sales, buyer tidak bisa resell, tidak ada komisi, ownership tetap dengan seller.</p>',
                'summary' => 'Panduan lengkap sistem mode penjualan dengan Scarcity dan Standard mode.',
                'category' => 'wiki',
                'icon' => 'heroicons-outline:shopping-cart',
                'links' => ['/docs/sale-mode-scarcity', '/docs/sale-mode-standard', '/docs/repurchase-guide'],
                'screenshots' => ['docs/screenshots/sale-mode-selection.png'],
                'video_urls' => [],
                'tags' => ['sale-mode', 'scarcity', 'standard', 'resale', 'repurchase'],
                'order' => 4,
                'is_active' => true,
                'view_count' => 45,
                'helpful_count' => 18,
            ],
            // Marketplace & Purchasing
            [
                'slug' => 'marketplace-buying-guide',
                'title' => 'Panduan Membeli Catatan di Marketplace',
                'content' => '<p>Pelajari cara mencari, memfilter, dan membeli catatan di marketplace. Termasuk cara menggunakan search, filter by category, dan memahami preview content.</p>',
                'summary' => 'Cara membeli dan mengakses catatan dari marketplace.',
                'category' => 'wiki',
                'icon' => 'heroicons-outline:shopping-bag',
                'links' => ['/marketplace', '/docs/purchase-flow'],
                'screenshots' => ['docs/screenshots/marketplace-search.png'],
                'video_urls' => [],
                'tags' => ['marketplace', 'buyer', 'purchase'],
                'order' => 5,
                'is_active' => true,
                'view_count' => 112,
                'helpful_count' => 35,
            ],
            // Premium Subscriptions
            [
                'slug' => 'premium-subscription',
                'title' => 'Premium Subscription & Benefits',
                'content' => '<p>Pelajari manfaat Premium subscription, cara upgrade, dan fitur-fitur eksklusif yang tersedia untuk premium users seperti unlimited downloads, priority support, dan discount pembelian.</p>',
                'summary' => 'Manfaat dan cara menggunakan Premium subscription.',
                'category' => 'wiki',
                'icon' => 'heroicons-outline:star',
                'links' => ['/subscription', '/docs/premium-benefits'],
                'screenshots' => ['docs/screenshots/premium-dashboard.png'],
                'video_urls' => [],
                'tags' => ['premium', 'subscription', 'benefits'],
                'order' => 6,
                'is_active' => true,
                'view_count' => 89,
                'helpful_count' => 28,
            ],
            // Referral System
            [
                'slug' => 'referral-program',
                'title' => 'Program Referral & Komisi',
                'content' => '<p>Pelajari cara menggunakan referral code, mendapatkan komisi dari referral, dan strategi untuk memaksimalkan earning dari program referral.</p>',
                'summary' => 'Cara menggunakan dan mendapatkan komisi dari referral program.',
                'category' => 'wiki',
                'icon' => 'heroicons-outline:user-group',
                'links' => ['/referral', '/docs/referral-commission'],
                'screenshots' => ['docs/screenshots/referral-dashboard.png'],
                'video_urls' => [],
                'tags' => ['referral', 'commission', 'earning'],
                'order' => 7,
                'is_active' => true,
                'view_count' => 67,
                'helpful_count' => 22,
            ],
            // Collections
            [
                'slug' => 'collections-management',
                'title' => 'Kelola Collections & Organisasi Catatan',
                'content' => '<p>Pelajari cara membuat collections, menambahkan catatan ke collections, dan mengorganisir catatan yang sudah dibeli dengan lebih baik.</p>',
                'summary' => 'Cara menggunakan collections untuk mengorganisir catatan.',
                'category' => 'wiki',
                'icon' => 'heroicons-outline:folder',
                'links' => ['/collections', '/docs/collections-tips'],
                'screenshots' => ['docs/screenshots/collections-view.png'],
                'video_urls' => [],
                'tags' => ['collections', 'organization', 'notes'],
                'order' => 8,
                'is_active' => true,
                'view_count' => 54,
                'helpful_count' => 19,
            ],
            // Reviews & Ratings
            [
                'slug' => 'reviews-and-ratings',
                'title' => 'Sistem Review & Rating',
                'content' => '<p>Pelajari cara memberikan review dan rating untuk catatan yang sudah dibeli, serta cara melihat review dari buyer lain sebelum membeli.</p>',
                'summary' => 'Cara menggunakan sistem review dan rating.',
                'category' => 'wiki',
                'icon' => 'heroicons-outline:star',
                'links' => ['/docs/review-guidelines'],
                'screenshots' => ['docs/screenshots/review-form.png'],
                'video_urls' => [],
                'tags' => ['review', 'rating', 'feedback'],
                'order' => 9,
                'is_active' => true,
                'view_count' => 43,
                'helpful_count' => 15,
            ],
            // Support Tickets
            [
                'slug' => 'support-tickets',
                'title' => 'Support Ticket System',
                'content' => '<p>Pelajari cara membuat support ticket, melacak status ticket, dan berkomunikasi dengan tim support untuk mendapatkan bantuan.</p>',
                'summary' => 'Cara menggunakan sistem support ticket.',
                'category' => 'wiki',
                'icon' => 'heroicons-outline:chat-bubble-left-right',
                'links' => ['/support', '/docs/support-guidelines'],
                'screenshots' => ['docs/screenshots/support-ticket.png'],
                'video_urls' => [],
                'tags' => ['support', 'ticket', 'help'],
                'order' => 10,
                'is_active' => true,
                'view_count' => 38,
                'helpful_count' => 12,
            ],
            // Forum
            [
                'slug' => 'forum-community',
                'title' => 'Forum & Komunitas',
                'content' => '<p>Pelajari cara menggunakan forum untuk berdiskusi, berbagi tips, dan berinteraksi dengan komunitas Noteds. Termasuk cara membuat post, comment, dan bookmark.</p>',
                'summary' => 'Cara menggunakan forum dan fitur komunitas.',
                'category' => 'wiki',
                'icon' => 'heroicons-outline:chat-bubble-oval-left',
                'links' => ['/forum', '/docs/forum-guidelines'],
                'screenshots' => ['docs/screenshots/forum-view.png'],
                'video_urls' => [],
                'tags' => ['forum', 'community', 'discussion'],
                'order' => 11,
                'is_active' => true,
                'view_count' => 52,
                'helpful_count' => 17,
            ],
            // Public Profiles
            [
                'slug' => 'public-profiles',
                'title' => 'Public Profile & AI Chat',
                'content' => '<p>Pelajari cara mengatur public profile, menggunakan AI Chat untuk bertanya kepada seller, dan memaksimalkan visibility profile Anda.</p>',
                'summary' => 'Cara menggunakan public profile dan AI Chat feature.',
                'category' => 'wiki',
                'icon' => 'heroicons-outline:user-circle',
                'links' => ['/docs/profile-setup', '/docs/ai-chat-guide'],
                'screenshots' => ['docs/screenshots/public-profile.png'],
                'video_urls' => [],
                'tags' => ['profile', 'ai-chat', 'visibility'],
                'order' => 12,
                'is_active' => true,
                'view_count' => 41,
                'helpful_count' => 14,
            ],
            // Featured Notes
            [
                'slug' => 'featured-notes',
                'title' => 'Featured Notes Advertising',
                'content' => '<p>Pelajari cara mengajukan featured placement untuk catatan Anda, memahami pricing per location, dan memaksimalkan ROI dari featured advertising.</p>',
                'summary' => 'Cara menggunakan featured notes untuk meningkatkan visibility.',
                'category' => 'wiki',
                'icon' => 'heroicons-outline:megaphone',
                'links' => ['/docs/featured-notes-guide', '/docs/featured-pricing'],
                'screenshots' => ['docs/screenshots/featured-request.png'],
                'video_urls' => [],
                'tags' => ['featured', 'advertising', 'marketing'],
                'order' => 13,
                'is_active' => true,
                'view_count' => 29,
                'helpful_count' => 11,
            ],
            // Buyer Analytics
            [
                'slug' => 'buyer-analytics',
                'title' => 'Buyer Analytics Dashboard',
                'content' => '<p>Pelajari cara menggunakan buyer analytics untuk melacak purchase statistics, download statistics, completion rate, dan insights lainnya.</p>',
                'summary' => 'Cara menggunakan buyer analytics dashboard.',
                'category' => 'wiki',
                'icon' => 'heroicons-outline:chart-bar',
                'links' => ['/docs/buyer-analytics-guide'],
                'screenshots' => ['docs/screenshots/buyer-analytics.png'],
                'video_urls' => [],
                'tags' => ['analytics', 'buyer', 'statistics'],
                'order' => 14,
                'is_active' => true,
                'view_count' => 33,
                'helpful_count' => 10,
            ],
            // Note Conversations
            [
                'slug' => 'note-conversations',
                'title' => 'Note Conversations & Messaging',
                'content' => '<p>Pelajari cara berkomunikasi dengan seller melalui note conversations, mengajukan pertanyaan, dan mendapatkan support langsung dari seller.</p>',
                'summary' => 'Cara menggunakan note conversations untuk komunikasi dengan seller.',
                'category' => 'wiki',
                'icon' => 'heroicons-outline:envelope',
                'links' => ['/note-conversations', '/docs/conversation-etiquette'],
                'screenshots' => ['docs/screenshots/note-conversation.png'],
                'video_urls' => [],
                'tags' => ['conversation', 'messaging', 'communication'],
                'order' => 15,
                'is_active' => true,
                'view_count' => 27,
                'helpful_count' => 9,
            ],
            // Reading Progress
            [
                'slug' => 'reading-progress',
                'title' => 'Reading Progress & History',
                'content' => '<p>Pelajari cara melacak reading progress, melihat reading history, dan menggunakan fitur untuk mengorganisir catatan yang sedang dibaca.</p>',
                'summary' => 'Cara menggunakan reading progress dan history tracking.',
                'category' => 'wiki',
                'icon' => 'heroicons-outline:book-open',
                'links' => ['/docs/reading-progress-guide'],
                'screenshots' => ['docs/screenshots/reading-progress.png'],
                'video_urls' => [],
                'tags' => ['reading', 'progress', 'history'],
                'order' => 16,
                'is_active' => true,
                'view_count' => 24,
                'helpful_count' => 8,
            ],
            // Workspace
            [
                'slug' => 'workspace-collaboration',
                'title' => 'Workspace & Kolaborasi',
                'content' => '<p>Pelajari cara membuat workspace, mengundang anggota, dan berkolaborasi dalam workspace untuk mengelola catatan bersama.</p>',
                'summary' => 'Cara menggunakan workspace dan fitur kolaborasi.',
                'category' => 'wiki',
                'icon' => 'heroicons-outline:users',
                'links' => ['/workspace', '/docs/workspace-guide'],
                'screenshots' => ['docs/screenshots/workspace-view.png'],
                'video_urls' => [],
                'tags' => ['workspace', 'collaboration', 'team'],
                'order' => 17,
                'is_active' => true,
                'view_count' => 31,
                'helpful_count' => 11,
            ],
            // Follow System
            [
                'slug' => 'follow-system',
                'title' => 'Follow & Social Features',
                'content' => '<p>Pelajari cara follow seller favorit, melihat aktivitas mereka, dan menggunakan fitur sosial untuk terhubung dengan komunitas.</p>',
                'summary' => 'Cara menggunakan follow system dan fitur sosial.',
                'category' => 'wiki',
                'icon' => 'heroicons-outline:heart',
                'links' => ['/docs/follow-guide'],
                'screenshots' => ['docs/screenshots/follow-view.png'],
                'video_urls' => [],
                'tags' => ['follow', 'social', 'community'],
                'order' => 18,
                'is_active' => true,
                'view_count' => 19,
                'helpful_count' => 7,
            ],
            // Bookmarks
            [
                'slug' => 'bookmarks',
                'title' => 'Bookmarks & Saved Items',
                'content' => '<p>Pelajari cara bookmark post di forum, menyimpan catatan favorit, dan mengorganisir bookmark untuk akses cepat.</p>',
                'summary' => 'Cara menggunakan bookmarks untuk menyimpan konten favorit.',
                'category' => 'wiki',
                'icon' => 'heroicons-outline:bookmark',
                'links' => ['/forum/bookmarks', '/docs/bookmarks-guide'],
                'screenshots' => ['docs/screenshots/bookmarks-view.png'],
                'video_urls' => [],
                'tags' => ['bookmark', 'save', 'favorites'],
                'order' => 19,
                'is_active' => true,
                'view_count' => 22,
                'helpful_count' => 8,
            ],
            // Tax & Pricing
            [
                'slug' => 'tax-and-pricing',
                'title' => 'Tax Rules & Dynamic Pricing',
                'content' => '<p>Pelajari cara sistem tax bekerja berdasarkan country dan category, serta cara menggunakan dynamic pricing guidance untuk menentukan harga optimal.</p>',
                'summary' => 'Pemahaman tentang tax rules dan dynamic pricing system.',
                'category' => 'wiki',
                'icon' => 'heroicons-outline:calculator',
                'links' => ['/docs/tax-guide', '/docs/pricing-strategy'],
                'screenshots' => ['docs/screenshots/tax-breakdown.png'],
                'video_urls' => [],
                'tags' => ['tax', 'pricing', 'strategy'],
                'order' => 20,
                'is_active' => true,
                'view_count' => 36,
                'helpful_count' => 13,
            ],
            // Content Protection
            [
                'slug' => 'content-protection',
                'title' => 'Content Protection & Security',
                'content' => '<p>Pelajari cara sistem content protection bekerja, termasuk preview terbatas, secure file uploads, download control, dan duplicate content protection.</p>',
                'summary' => 'Pemahaman tentang sistem content protection dan security.',
                'category' => 'wiki',
                'icon' => 'heroicons-outline:shield-check',
                'links' => ['/docs/content-protection-guide'],
                'screenshots' => ['docs/screenshots/content-protection.png'],
                'video_urls' => [],
                'tags' => ['security', 'protection', 'content'],
                'order' => 21,
                'is_active' => true,
                'view_count' => 28,
                'helpful_count' => 10,
            ],
            // Internationalization
            [
                'slug' => 'internationalization',
                'title' => 'Multi-Language & Currency',
                'content' => '<p>Pelajari cara menggunakan fitur multi-language (EN, ID, AR) dan multi-currency (USD, IDR) untuk pengalaman yang lebih personal.</p>',
                'summary' => 'Cara menggunakan fitur internationalization.',
                'category' => 'wiki',
                'icon' => 'heroicons-outline:globe-alt',
                'links' => ['/docs/i18n-guide'],
                'screenshots' => ['docs/screenshots/language-selector.png'],
                'video_urls' => [],
                'tags' => ['i18n', 'language', 'currency'],
                'order' => 22,
                'is_active' => true,
                'view_count' => 15,
                'helpful_count' => 6,
            ],
        ];
    }
}
